/* Generated by scripts/gen-types.mjs from schema/*.schema.json. Do not edit. */

/**
 * Author notes. Never rendered. Use them to flag placeholders.
 */
export type Notes = string | string[];
export type Id = string;
/**
 * An id, or "@group".
 */
export type Ref = string;
export type RefList = Ref[];
/**
 * [x, y, width, height] in map units.
 *
 * @minItems 4
 * @maxItems 4
 */
export type Rect = [number, number, number, number];
/**
 * Lenses that show this element. Omitted means every lens; [] means parked (kept in the data, never shown).
 */
export type Lenses = Id[];
/**
 * @minItems 2
 * @maxItems 2
 */
export type Point = [number, number];
/**
 * Top-left of the bounding box, for every kind.
 *
 * @minItems 2
 * @maxItems 2
 */
export type Point1 = [number, number];
/**
 * Bounding box [width, height].
 *
 * @minItems 2
 * @maxItems 2
 */
export type Size = [number, number];
/**
 * Lenses in which this pill fades out.
 */
export type IdList = Id[];
export type Row =
  | string
  | {
      id?: Id;
      text: string;
      notes?: Notes;
    };
/**
 * Lenses that show this element. Omitted means every lens; [] means parked (kept in the data, never shown).
 */
export type Lenses1 = Id[];
/**
 * [x, y, width, height] in map units.
 *
 * @minItems 4
 * @maxItems 4
 */
export type Rect1 = [number, number, number, number];
/**
 * Layers switched on in this scene.
 */
export type IdList1 = Id[];
export type Effect = {
  type: 'cycleRows' | 'highlightRow';
} & Effect1;
export type Effect1 =
  | {
      type: 'cycleRows';
      node: Id;
      /**
       * Seconds per row. Defaults to the theme.
       */
      interval?: number;
    }
  | {
      type: 'highlightRow';
      node: Id;
      /**
       * A row id.
       */
      row: string;
    };

/**
 * A journey or architecture described as data: nodes, edges, labels and panels on one map, viewed through lenses, walked through as scenes.
 */
export interface WayforgeJourney {
  $schema?: string;
  version: 1;
  meta: Meta;
  /**
   * A built-in theme name (themes/<name>.json) or a path relative to the journey file.
   */
  theme?: string;
  /**
   * Deep-partial theme merged over the chosen theme. The merged theme is validated against theme.schema.json.
   */
  themeOverrides?: {};
  ui?: Ui;
  /**
   * Ordered. Order sets the lens buttons and the number keys 1..n.
   *
   * @minItems 1
   */
  lenses: [Lens, ...Lens[]];
  layers?: Layer[];
  /**
   * Global order of scene keys, used to keep the presenter's place when switching lenses.
   *
   * @minItems 1
   */
  stageOrder: [Id, ...Id[]];
  /**
   * Named id lists. Reference one inside a scene's active lists as "@name". Groups may include other groups.
   */
  groups?: {
    [k: string]: RefList | undefined;
  };
  panels?: Panel[];
  /**
   * Array order is paint order.
   */
  nodes: Node[];
  /**
   * Array order is paint order.
   */
  edges: Edge[];
  labels?: Label[];
  /**
   * One ordered scene list per lens id.
   */
  scenes: {
    [k: string]: Scene[] | undefined;
  };
  notes?: Notes;
}
export interface Meta {
  title: string;
  brand?: string;
  /**
   * Accessible description of the whole map (SVG aria-label).
   */
  description?: string;
  lang?: string;
  /**
   * An emoji or a data: URI.
   */
  favicon?: string | null;
  notes?: Notes;
}
/**
 * Interface strings. {keys}, {n} and {label} are substituted.
 */
export interface Ui {
  back?: string;
  next?: string;
  fullscreen?: string;
  hint?: string;
  lensGroup?: string;
  steps?: string;
  step?: string;
}
export interface Lens {
  id: Id;
  label: string;
  default?: boolean;
  notes?: Notes;
}
export interface Layer {
  id: Id;
  /**
   * A tone name defined by the theme.
   */
  tone: string;
  /**
   * Opacity factor for this layer's elements while a scene has the layer switched off.
   */
  ghost: number;
  notes?: Notes;
}
export interface Panel {
  id: Id;
  rect: Rect;
  /**
   * A tone name defined by the theme.
   */
  tone: string;
  layer?: Id;
  lenses?: Lenses;
  title?: {
    text: string;
    at: Point;
  };
  notes?: Notes;
}
export interface Node {
  id: Id;
  kind: 'box' | 'circle' | 'diamond' | 'container';
  at: Point1;
  size: Size;
  title: string;
  subtitle?: string;
  layer?: Id;
  /**
   * A tone name defined by the theme.
   */
  tone?: string;
  outline?: 'normal' | 'strong';
  pills?: Pill[];
  /**
   * Containers only.
   */
  rows?: Row[];
  /**
   * Containers only. outline: rows take the node's outline while active. tint: rows fill with the tone's soft color while active.
   */
  rowStyle?: 'outline' | 'tint';
  lenses?: Lenses;
  /**
   * Translate the node by [dx, dy] in specific lenses. Animated with a glide.
   */
  offsetByLens?: {
    [k: string]: Point | undefined;
  };
  metrics?: NodeMetrics;
  notes?: Notes;
}
/**
 * A small label straddling the node's top edge, right-aligned. Names the platform or owner.
 */
export interface Pill {
  text: string;
  /**
   * A tone name defined by the theme.
   */
  tone: string;
  /**
   * Defaults to round(chars x charWidth + padding) from the theme.
   */
  width?: number;
  hideIn?: IdList;
  notes?: Notes;
}
/**
 * Per-node override of the theme's metrics for this node's kind.
 */
export interface NodeMetrics {
  radius?: number;
  inset?: number;
  titleDy?: number;
  titleDySub?: number;
  subDy?: number;
  subGap?: number;
  titleOffset?: Point;
  rowsTop?: number;
  rowInset?: number;
  rowTextInset?: number;
  rowHeight?: number;
  rowPitch?: number;
  rowRadius?: number;
}
export interface Edge {
  id: Id;
  /**
   * SVG path data in map units.
   */
  path: string;
  layer?: Id;
  /**
   * A tone name defined by the theme.
   */
  tone?: string;
  dashed?: boolean;
  /**
   * Draws nothing. Used inside packet routes to carry a packet through a node.
   */
  hidden?: boolean;
  lenses?: Lenses;
  notes?: Notes;
}
/**
 * Text attached to an edge. Full strength while the edge is active, dimmed otherwise.
 */
export interface Label {
  id?: Id;
  edge: Id;
  at: Point;
  text: string;
  anchor?: 'start' | 'middle' | 'end';
  /**
   * Defaults to the edge's layer.
   */
  layer?: string;
  lenses?: Lenses1;
  notes?: Notes;
}
export interface Scene {
  /**
   * The stage this scene represents. Must appear in stageOrder.
   */
  key: string;
  /**
   * Step dot tooltip.
   */
  label: string;
  title: string;
  caption: string;
  camera: Rect1;
  layers?: IdList1;
  active: {
    nodes?: RefList;
    edges?: RefList;
  };
  routes?: Route[];
  effects?: Effect[];
  /**
   * An establishing shot. Exempt from the readability lint.
   */
  wide?: boolean;
  notes?: Notes;
}
export interface Route {
  /**
   * @minItems 1
   */
  edges: [Id, ...Id[]];
  /**
   * Seconds added to the clock for this packet, so packets in one scene are staggered.
   */
  phase?: number;
  /**
   * Draw this packet fainter.
   */
  dim?: boolean;
  notes?: Notes;
}

export type Unit = number;
/**
 * Title baseline position from the container's top-left.
 *
 * @minItems 2
 * @maxItems 2
 */
export type Pair = [number, number];
/**
 * @minItems 2
 * @maxItems 2
 */
export type Pair1 = [number, number];

/**
 * Design tokens: colors for light and dark, tones, fonts, metrics, motion and packet style.
 */
export interface WayforgeTheme {
  $schema?: string;
  fonts: {
    heading: Font;
    text: Font;
  };
  /**
   * CSS custom properties (names without the leading --) for each color scheme.
   */
  colors: {
    light: Palette;
    dark: Palette;
  };
  /**
   * Tone for active elements with no layer or tone of their own, and for interface accents.
   */
  defaultTone: string;
  /**
   * Named accent tones, each pointing at color variables.
   */
  tones: {
    [k: string]:
      | {
          /**
           * Variable for strokes, pills and panel outlines.
           */
          color: string;
          /**
           * Variable for row fills and highlights.
           */
          soft?: string;
          /**
           * Variable for panel fills.
           */
          panel?: string;
        }
      | undefined;
  };
  /**
   * Base opacity of inactive elements, and the factor for dim packets.
   */
  opacity: {
    node: Unit;
    edge: Unit;
    label: Unit;
    dim: Unit;
  };
  metrics: {
    box: {
      radius: number;
      /**
       * Left inset of title and subtitle.
       */
      inset: number;
      /**
       * Title baseline below center when there is no subtitle.
       */
      titleDy: number;
      /**
       * Title baseline below center when there is a subtitle.
       */
      titleDySub: number;
      /**
       * Subtitle baseline below center.
       */
      subDy: number;
      /**
       * Outline width of every node shape.
       */
      stroke: number;
      /**
       * Active outline width for outline: strong.
       */
      strongStroke: number;
    };
    circle: RoundShape;
    diamond: RoundShape;
    container: {
      radius: number;
      titleOffset: Pair;
      /**
       * Top of the first row from the container's top.
       */
      rowsTop: number;
      /**
       * Horizontal inset of rows from the container's edges.
       */
      rowInset: number;
      /**
       * Row text inset from the row's left edge.
       */
      rowTextInset: number;
      rowHeight: number;
      rowPitch: number;
      rowRadius: number;
      /**
       * Row text baseline from the row's top.
       */
      rowTextDy: number;
      rowStroke: number;
      highlightFillOpacity: number;
      highlightStroke: number;
    };
    pill: {
      height: number;
      /**
       * Gap between the pill's right end and the node's right edge.
       */
      inset: number;
      charWidth: number;
      padding: number;
      /**
       * Text baseline below the node's top edge.
       */
      textDy: number;
    };
    edge: {
      stroke: number;
      activeStroke: number;
      dash: Pair1;
    };
    panel: {
      radius: number;
      stroke: number;
      dash: Pair1;
    };
    /**
     * Font sizes in map units.
     */
    type: {
      title: number;
      subtitle: number;
      containerTitle: number;
      row: number;
      label: number;
      panelTitle: number;
      pill: number;
    };
  };
  /**
   * Durations in seconds unless noted.
   */
  motion: {
    /**
     * Opacity transitions of nodes, edges and labels.
     */
    fade: number;
    /**
     * Opacity transitions of panels.
     */
    decorFade: number;
    /**
     * Node outline color transition.
     */
    stroke: number;
    /**
     * Per-lens node movement.
     */
    glide: number;
    glideEase: string;
    /**
     * Camera move, cubic ease in-out.
     */
    camera: number;
    /**
     * Caption fade-out before the text swaps.
     */
    caption: number;
    pillFade: number;
    /**
     * Row fill and stroke transitions.
     */
    row: number;
    /**
     * Default seconds per row for cycleRows.
     */
    rowCycle: number;
    /**
     * Minimum horizontal swipe in CSS pixels.
     */
    swipe: number;
  };
  packet: {
    /**
     * Map units per second.
     */
    speed: number;
    /**
     * Seconds to wait after a route finishes before repeating.
     */
    hold: number;
    /**
     * Number of dots including the head.
     */
    tail: number;
    /**
     * Spacing of tail dots in map units.
     */
    gap: number;
    /**
     * Fade-in and fade-out distance at each end of a route.
     */
    fade: number;
    headRadius: number;
    radiusStep: number;
    minRadius: number;
    glowRadius: number;
    glowBlur: number;
    glowOpacity: number;
    /**
     * Where the static packet sits along its route with reduced motion (0..1).
     */
    reducedMotionAt: number;
  };
  background: {
    gridDot: number;
    gridSpacing: number;
  };
  lint: {
    /**
     * Smallest acceptable on-screen text size.
     */
    minTextPx: number;
    /**
     * Screen width in CSS pixels assumed by the readability lint.
     */
    referenceScreenWidth: number;
  };
}
export interface Font {
  family: string;
  /**
   * @minItems 1
   */
  weights: [number, ...number[]];
  /**
   * Load this family from Google Fonts.
   */
  google?: boolean;
  fallback: string;
}
export interface Palette {
  [k: string]: string | undefined;
}
export interface RoundShape {
  /**
   * Title baseline below center.
   */
  titleDy: number;
  /**
   * Subtitle baseline below the shape's bottom.
   */
  subGap: number;
}
