// Generates src/model/schema-types.ts from the published JSON Schemas, so the
// schemas stay the single source of truth.
import { compileFromFile } from 'json-schema-to-typescript';
import { writeFileSync } from 'node:fs';

const opts = {
  bannerComment: '',
  additionalProperties: false,
  strictIndexSignatures: true,
  style: { singleQuote: true },
};
const journey = await compileFromFile('schema/journey.schema.json', opts);
const theme = await compileFromFile('schema/theme.schema.json', opts);
const banner = '/* Generated by scripts/gen-types.mjs from schema/*.schema.json. Do not edit. */\n\n';
writeFileSync('src/model/schema-types.ts', banner + journey + '\n' + theme);
